# Generated by Django 5.2.17 on 2026-08-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asistencia',
            field=models.CharField(blank=True, choices=[('asistio', 'Sí llegó'), ('no_asistio', 'No llegó')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='reservas.reserva'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('reserva', 'calificado_por'), name='una_calificacion_por_lado_y_reserva'),
        ),
    ]
