# Generated by Django 5.2.17 on 2026-08-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancha',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canchas.deporte'),
        ),
        migrations.AddField(
            model_name='fotocancha',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='canchas.cancha'),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha'),
        ),
    ]
